zalo:
  # Đường dẫn tới source lua
  pathSourceLua: "/ZaloClientLua"

  # Đường dẫn tới dữ liệu tài khoản, thư mục chứa các thông tin tài khoản
  pathDataAccount: "/data/account/"

  # Xác định có lắng nghe sự kiện từ chính tài khoản này hay không
  # Nếu giá trị là false, sẽ không lắng nghe sự kiện từ bản thân
  selfListen: false

  # Phiên bản API sử dụng. Nếu giá trị là -1, sẽ sử dụng giá trị mặc định là 642
  # Nếu bạn cần sử dụng phiên bản khác, thay đổi giá trị này
  apiVersion: -1

  # Loại API sử dụng. Nếu giá trị là -1, sẽ sử dụng giá trị mặc định là 30
  # Thay đổi giá trị này nếu bạn cần sử dụng loại API khác
  apiType: -1

  # Cấu hình tự động kết nối lại khi gặp lỗi Ping-Pong hoặc mất kết nối
  # Nếu là true, sẽ tự động kết nối lại khi có sự cố xảy ra
  listenerAutoReconnectOnFailurePingPong: true

  # Cấu hình Zalo ID của người quản trị chính (Master ID).
  # Đây là ID của người dùng được chỉ định có quyền quản lý cao nhất trong việc xử lý các sự kiện và tin nhắn.
  idMaster: "8577675992826788959"

  # Danh sách ID của các nhóm mà bot sẽ lắng nghe và xử lý sự kiện.
  # Lưu ý: Mỗi tài khoản Zalo sẽ có ID nhóm khác nhau ngay cả khi tham gia cùng một nhóm.
  # Ví dụ: Một nhóm ABC có thể có ID "50248...." với tài khoản A, nhưng lại có ID "2482748...." với tài khoản B.
  # Vì vậy, cần cấu hình lại danh sách ID nhóm khi thay đổi tài khoản sử dụng.
  idGroupActive:
    - "5090396119491093489"
    - "5401995638456220834"
